version: '3'
services:
  webserver:
    build: ./G_Backend
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080

  admin:
    build: ./G_Admin
    ports:
      - "3000:3000"
    command: npm run start

  user_tech:
    build: ./G_User-Tech
    ports:
      - "3001:3000"
    command: npm run start
