services:
  web:
    build: ./G_Backend
    command: python manage.py runserver 0.0.0.0:8080
    expose:
      - "8080"

  admin:
    build: ./G_Admin
    ports:
      - "3000:3000"
    command: npm run start

  user-tech:
    build: ./G_User-Tech
    ports:
      - "3001:3000"
    command: npm run start
